<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-66</name>
   <tag></tag>
   <elementGuidId>28c19acc-29b1-4bc9-a460-f2a3e7d91d6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-66</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-66']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8501e499-a184-4a0f-a4b8-6441d2913d41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-66</value>
      <webElementGuid>08d5bf82-be34-4917-a23d-129ae4fec257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>93e0b10e-a6a8-4352-86b6-2a2a78000dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-66&quot;)</value>
      <webElementGuid>98b6c1a4-591e-44cc-a242-7eb72f8a5c3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-66']</value>
      <webElementGuid>3ea7b01c-94a6-498c-8991-436ad6829780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/form/div[2]/div/div/div/input</value>
      <webElementGuid>1453c646-379a-440c-b3b5-d8b290d60709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>ab350c8c-8eb0-409e-91b3-6922c7cc9090</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-66' and @type = 'password']</value>
      <webElementGuid>03d32570-057e-4c90-8ca4-5eaaf7dfc18f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
