<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-72</name>
   <tag></tag>
   <elementGuidId>a32d89a8-0c3b-4787-a0b3-15f2701c8d97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-72</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-72']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0ce63b89-ea76-4f3b-b9b5-652f77bfb508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-72</value>
      <webElementGuid>6fcf9831-52d1-4dbd-9d36-500eafb05ac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f8d14a5e-ad30-48fd-90bd-fc1d844dd8f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-72&quot;)</value>
      <webElementGuid>a173e051-ebea-4860-b08a-864284345308</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-72']</value>
      <webElementGuid>98f40124-5192-462c-974f-5004a9a4bcaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/form/div[4]/div/div/div/input</value>
      <webElementGuid>a84b80ca-53fb-4017-9087-7c1adb62ca0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/input</value>
      <webElementGuid>d85c2217-e85f-44ad-9306-288bbf99e373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-72' and @type = 'text']</value>
      <webElementGuid>e2bc88dc-b19c-44d7-8146-74046cf813a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
