<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-75</name>
   <tag></tag>
   <elementGuidId>45f45d2e-ba12-43f9-996f-2188b2119120</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-75</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-75']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>160ce352-51ed-48c5-ae66-2cedc5287671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-75</value>
      <webElementGuid>1f2f1cc1-063e-465a-a132-46f45dfefb08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>31dd4c46-0991-46a8-85cf-1b59ec7544e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-75&quot;)</value>
      <webElementGuid>644ffdce-79aa-4652-95fd-e22acd9230e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-75']</value>
      <webElementGuid>888febd6-f9bf-4c05-9c25-33de9387d13b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/form/div[5]/div/div/div/input</value>
      <webElementGuid>86781d9c-5ee8-4085-9809-2a488cd589d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/input</value>
      <webElementGuid>8ea158bf-a05f-4cf2-8d97-5898bbeb9f1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-75' and @type = 'text']</value>
      <webElementGuid>d09b3bf1-3e91-4bbf-973e-399de1eb4a46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
