<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-63</name>
   <tag></tag>
   <elementGuidId>d6a40930-3105-4c11-918c-28826259a7a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-63</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-63']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>37041232-cac6-43dc-be4d-aae4eb76ed75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-63</value>
      <webElementGuid>c61a82a1-076c-4a02-926f-bdedf82baac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bb97dded-51ef-477d-bda9-98a214f13444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-63&quot;)</value>
      <webElementGuid>5f288d54-494d-444e-83ff-3ca43dfffcde</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-63']</value>
      <webElementGuid>b9dc5615-c8e2-482a-96c0-d1d977e514c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/form/div/div/div/div/input</value>
      <webElementGuid>2bffe54a-d633-44ca-a3fd-6cc9b0f2fd2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>056177c3-be16-469b-971e-2676284ad7eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-63' and @type = 'text']</value>
      <webElementGuid>9487bd2d-a995-4c38-b38d-e1d7b19ba596</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
