<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-78</name>
   <tag></tag>
   <elementGuidId>db3e4dba-8acd-43ca-9d6d-0752fb6d9503</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-78</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-78']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>608582d6-9868-43d2-96a1-b623428ac0f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-78</value>
      <webElementGuid>9cc826f0-3c25-40e6-90dc-1cc4442af607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4042b29f-659a-451a-8450-14b627745c06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-78&quot;)</value>
      <webElementGuid>29947f52-af1b-4640-a05e-43ef935907d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-78']</value>
      <webElementGuid>2ef6d800-99d9-41db-af6c-bd1e7dff075d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/form/div[6]/div/div/div/input</value>
      <webElementGuid>76408599-615e-41d3-a4cf-988d9de66910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/input</value>
      <webElementGuid>81a55329-e08e-4338-8d6a-ef9cfa8767b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-78' and @type = 'text']</value>
      <webElementGuid>a1133714-0891-4833-b2c5-c08bfaf4b1c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
