<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-69</name>
   <tag></tag>
   <elementGuidId>ad9b09e1-1604-44e2-bf10-8b7acd2c23d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-69</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-69']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6aed3246-0621-452d-b79c-1231c1c215d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-69</value>
      <webElementGuid>c2eb41f0-8a73-497d-b2ea-7756e0602689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>b994abc0-9a6e-4da2-9094-183754bcf81f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-69&quot;)</value>
      <webElementGuid>68acf5e7-2bf0-4b39-a30a-43796d3660cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-69']</value>
      <webElementGuid>ee661a8a-7fb2-4f6f-80b7-e92d816d741a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/form/div[3]/div/div/div/input</value>
      <webElementGuid>449db4aa-c4f6-4d3a-b259-48f24c076ff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>fafb9bb8-ec24-45f4-b119-a1d352912e8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-69' and @type = 'password']</value>
      <webElementGuid>1a0a3ee1-4815-4b20-9a48-2ac01590844e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
